### PR TITLE
Fix occupancy pyprismatic

### PR DESCRIPTION
**Pull request by ericpre**
- [x] Fix passing `includeOccupancy` in pyprismatic,
- [x] display and save simulation run time (optional).

### CODE REVIEW

**Comment by lerandc** [comment]
@ericpre since my ability to test these is a bit limited (considering cross-platform stuff in particular), but these look good and correct to me.  To improve organization of the repo and to keep the master clean for tagged released, I've created a new dev branch to stage changes. could you reopen the pull request to dev?

**Comment by ericpre** [comment]
To keep things tidy, can you reopen this PR so that we can change the base branch using the "edit" button?

**Comment by ericpre** [comment]
Thanks, base branch changed to `dev`.

**Comment by lerandc** [comment]
@ericpre slight changes to core.cpp to align the argument parsing in core.cpp for pyprismatic between this and #80 , could you verify real quick to make sure I got the order correct? Otherwise, good to merge

**Comment by ericpre** [comment]
Yes, this looks good to me; I have tweaked the docstring and default value of a few parameters.

**Comment by ericpre** [comment]
@lerandc, is it good to go?

**Comment by lerandc** [comment]
Woops, sorry!

**Pull request merged**
